name: Rotate Key Vault Secrets

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1 * *'  # This cron runs at midnight on the first day of every month (every 30 days)
    
permissions:   # Add this block at the top
  id-token: write
  contents: read
  
jobs:
  rotate-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure using Service Principal
      uses: azure/login@v2
      with:
        client-id: "5a8135af-d021-4674-bb9a-0cf077b1de63"
        tenant-id: "0852ffc6-85dc-42ba-a68b-465745925379"
        subscription-id: "c20dc67b-2597-434f-a423-f9c5155c18a8"
        allow-no-subscriptions: false
    
    - name: Generate new secret value (e.g., new DB password)
      id: generate-secret
      run: |
        # You can use any logic here to generate new secrets
        NEW_SECRET=$(openssl rand -base64 32)
        echo "NEW_SECRET=${NEW_SECRET}" >> $GITHUB_ENV

    - name: Set new secret in Key Vault
      run: |
        az keyvault secret set --vault-name dev-db-key-vault \
                               --name db-password \
                               --value ${{ env.NEW_SECRET }}

    - name: Log completion
      run: echo "Secret rotation complete!"
